In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/cars.csv")

df.head()

,brand,model_year,milage,fuel_type,transmission,accident,clean_title,price,horsepower,engine_capacity,layout,model,engine
0,Ford,2013,"51,000 mi.",E85 Flex Fuel,6-Speed A/T,At least 1 accident or damage reported,Yes,"$10,300",300.0,3.7,V6,Utility Police Interceptor Base,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...
1,Hyundai,2021,"34,742 mi.",Gasoline,8-Speed Automatic,At least 1 accident or damage reported,Yes,"$38,005",290.0,3.8,V6,Palisade SEL,3.8L V6 24V GDI DOHC
2,Lexus,2022,"22,372 mi.",Gasoline,Automatic,None reported,No,"$54,598",301.0,3.5,V6,RX 350 RX 350,3.5 Liter DOHC
3,INFINITI,2015,"88,900 mi.",Hybrid,7-Speed A/T,None reported,Yes,"$15,500",354.0,3.5,V6,Q50 Hybrid Sport,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...
4,Audi,2021,"9,835 mi.",Gasoline,8-Speed Automatic,None reported,No,"$34,999",333.0,2.0,I4,Q3 45 S line Premium Plus,2.0L I4 16V GDI DOHC Turbo

In [2]:
df.shape

(3918, 13)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3918 entries, 0 to 3917
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            3918 non-null   str
 1   model_year       3918 non-null   int64
 2   milage           3918 non-null   str
 3   fuel_type        3918 non-null   str
 4   transmission     3918 non-null   str
 5   accident         3918 non-null   str
 6   clean_title      3918 non-null   str
 7   price            3918 non-null   str
 8   horsepower       3918 non-null   float64
 9   engine_capacity  3918 non-null   float64
 10  layout           3918 non-null   str
 11  model            3918 non-null   str
 12  engine           3918 non-null   str
dtypes: float64(2), int64(1), str(10)
memory usage: 398.1 KB

In [4]:
df.describe(include="all")

,brand,model_year,milage,fuel_type,transmission,accident,clean_title,price,horsepower,engine_capacity,layout,model,engine
count,3918,3918.000000,3918,3918,3918,3918,3918,3918,3918.000000,3918.000000,3918,3918,3918
unique,56,NaN,2755,6,60,2,2,1545,NaN,NaN,17,1874,1139
top,Ford,NaN,"45,000 mi.",Gasoline,A/T,None reported,Yes,"$15,000",NaN,NaN,V6,M3 Base,2.0L I4 16V GDI DOHC Turbo
freq,379,NaN,15,3300,1006,2945,3349,37,NaN,NaN,1397,30,51
mean,NaN,2015.626850,NaN,NaN,NaN,NaN,NaN,NaN,336.514931,3.681738,NaN,NaN,NaN
std,NaN,5.843514,NaN,NaN,NaN,NaN,NaN,NaN,116.020949,1.392581,NaN,NaN,NaN
min,NaN,1996.000000,NaN,NaN,NaN,NaN,NaN,NaN,70.000000,0.650000,NaN,NaN,NaN
25%,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,265.000000,2.500000,NaN,NaN,NaN
50%,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,333.000000,3.500000,NaN,NaN,NaN
75%,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,395.000000,4.600000,NaN,NaN,NaN
max,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,1100.000000,8.400000,NaN,NaN,NaN

In [5]:
df.isnull().sum()

brand              0
model_year         0
milage             0
fuel_type          0
transmission       0
accident           0
clean_title        0
price              0
horsepower         0
engine_capacity    0
layout             0
model              0
engine             0
dtype: int64